version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    options: >-
      --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    options: >-
      --link mongodb:mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network