name: Jest Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js for backend
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # https://stackoverflow.com/questions/60176044
    - name: Create .env file
      working-directory: ./backend
      run: cp .env.development.example .env.test.local

    - name: Install dependencies for backend
      working-directory: ./backend
      run: npm install

    # https://github.com/marketplace/actions/docker-compose-action
    - name: Docker Compose Action
    # uses: hoverkraft-tech/compose-action@v2.0.1
    # with:
    #   compose-file: "./backend/compose.yml"
    #   up-flags: "-d"
      working-directory: ./backend
      run: docker compose up -d

    - name: Run backend tests
      working-directory: ./backend
      run: npm run test
