name: Jest Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    # strategy:
    #   matrix:
    #     node-version: [20, 21, 22]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js for backend
      uses: actions/setup-node@v4
      with:
    #     node-version: ${{ matrix.node-version }}
        node-version: '20'

    - name: Load environment file
      run: cp .env.development.example .env.test.local

    - name: Install dependencies
      run: npm install

    - name: Set up Docker Compose
      run: docker-compose -f compose.yml up -d

    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB to be ready..."
        while ! docker-compose logs mongodb | grep -q "waiting for connections"; do
          sleep 1
        done
      shell: bash

    - name: Run Jest tests
      run: npx dotenv -e .env.test.local npm test

    - name: Stop Docker Compose
      if: always()
      run: docker-compose -f compose.yml down
