name: Jest Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js for backend
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Load environment variables
      working-directory: ./backend
      run: |
        cp .env.development.example .env.test.local
        set -a
        source .env.test.local
        set +a
      shell: bash

    - name: Install dependencies for backend
      working-directory: ./backend
      run: npm install

    - name: Set up Docker Compose
      working-directory: ./backend
      run: docker-compose -f compose.yml up -d

    - name: Wait for MongoDB to be ready
      working-directory: ./backend
      run: |
        echo "Waiting for MongoDB to be ready..."
        while ! docker exec mongodb mongo --eval 'db.runCommand({ ping: 1 })' &>/dev/null; do
          sleep 1
        done
      shell: bash

    - name: Run backend tests
      working-directory: ./backend
      run: npm run test

    - name: Stop Docker Compose
      if: always()
      run: docker-compose -f compose.yml down
