name: Jest Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: ['20']
        mongodb-version: ['latest']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: rootuser
        mongodb-password: rootpass
        mongodb-port: 27017
        mongodb-container-name: mongodb

    - name: Install dependencies
      run: npm install

    - name: Load environment file
      run: cp .env.development.example .env.test.local

    - name: Run tests
      run: npm test
      env:
        CI: true
